cosmostation/cosmostation-ios

Cosmostation/Base/BaseConstant.swift, Cosmostation/Base/BaseNetWork.swift, Cosmostation/Base/BaseViewController.swift, Cosmostation/Cell/walletdash/WalletEvmosCell.xib, Cosmostation/Controller/GenTx/StepDelegateCheckViewController.swift, Cosmostation/Controller/GenTx/StepUndelegateCheckViewController.swift
=> [IOSWL] Support mainnet Evmos

Cosmostation/Controller/Main/Base.lproj/MainStoryboard.storyboard, Cosmostation/Controller/Main/ko.lproj/MainStoryboard.strings, Cosmostation/Controller/Setting/SettingTableViewController.swift, Cosmostation/Utils/WUtils.swift
IOSWL - Init notice by Setting
=> [IOSWL-153] Init notice fuc

Cosmostation/Controller/Main/Base.lproj/MainStoryboard.storyboard, Cosmostation/Controller/Setting/SettingTableViewController.swift, Cosmostation/Utils/WUtils.swift
IOS - Change position for notice & kava chainId
=> Ioswl 167 change notice

Cosmostation/Controller/Main/CommonWCViewController.swift
- change wc gas
- sign with eip155
=> [IOSWL-183] support evmos wallet connect

Cosmostation.xcodeproj/project.pbxproj, Cosmostation/Cell/Base.lproj/ClaimRewardAllCell.xib, Cosmostation/Cell/ClaimRewardAllCell.swift, Cosmostation/Controller/Main/AuthzDetailViewController.swift, Cosmostation/Controller/Main/AuthzListViewController.swift, Cosmostation/Controller/Main/MyValidatorViewController.swift, Cosmostation/Crypto/Signer.swift
=> [IOSWL-195]Easy mode for claim_reward, compounding

Cosmostation/Base/AppDelegate.swift, Cosmostation/Controller/Main/CommonWCViewController.swift
get account logic change, remove password input flow in dapptab
=> [IOSWL-198] improvement dapp

Cosmostation/Cell/walletdash/Base.lproj/WalletIrisCell.xib, Cosmostation/Cell/walletdash/WalletCrytoCell.xib, Cosmostation/Controller/GenTx/FeeGrpcViewController.swift
IOS - QA bug fixed(nft button gone, provenance gas amount)
=> [IOSWL] QA bug fixed(nft, provenance gas amount)

Cosmostation.xcodeproj/project.pbxproj, Cosmostation/Controller/GenTx/FeeGrpcViewController.swift, Cosmostation/Controller/GenTx/common/Transfer1ViewController.swift, Cosmostation/Controller/GenTx/common/Transfer5ViewController.swift, Cosmostation/Controller/Main/MainTabWalletViewController.swift, Cosmostation/Crypto/Signer.swift, Cosmostation/Dao/Cw20IbcTransferReq.swift, Cosmostation/Dao/MintscanPath.swift
juno -> osmosis cw20 transfer (neta, marble tested)
=> [IOSWL-115]Support Cw20 IBC transfer

Cosmostation/Base.lproj/Localizable.strings, Cosmostation/Model/ApiHistoryNewCustom.swift, Cosmostation/ko.lproj/Localizable.strings
IOS - Display Unknwon History List
=> [IOSWL-228] Display Unknown history list

Cosmostation/Dao/Param.swift
IOS - Inflation init with Axelar
=> [IOSWL-237] Inflation init with Axelar

Cosmostation/Controller/Main/MainTabWalletViewController.swift
=> [IOSWL] authz cell init with sif

Cosmostation/Cell/AuthzGranteeCell.xib, Cosmostation/Cell/AuthzGranterCell.xib, Cosmostation/Cell/GranterViewCell.xib, Cosmostation/Cell/walletdash/WalletAuthzCell.xib, Cosmostation/Cell/walletdash/WalletBaseChainCell.xib, Cosmostation/Controller/Main/AccountSwitchViewController.xib, Cosmostation/Controller/Main/CommonWCViewController.xib, Cosmostation/Controller/Main/token/StakingTokenGrpcViewController.xib
Fixed some English typos.
Make some buttons highlight when tapping them.
Fixed WalletAuthzCell constraint to avoid text draw outside of the view
=> Bugfix/minor UI fixes

Cosmostation/Controller/GenTx/FeeGrpcViewController.swift, Cosmostation/Controller/Main/MyValidatorViewController.swift
=> [IOSWL-244] update fee with chihuahua

Cosmostation.xcodeproj/project.pbxproj
project had warnings related to duplicated files in pbxproj, deleted and added again
=> fix pbxproj duplicates

Cosmostation/Controller/Setting/SettingTableViewController.swift
removed always true statement as current min deployment target is iOS13.5
=> removed #available iOS11

Cosmostation/Base/AppDelegate.swift, Cosmostation/Controller/GenTx/desmos/GenProfile0ViewController.swift, Cosmostation/Controller/GenTx/nft/GenNFT0ViewController.swift, Cosmostation/Controller/Main/nft/NFTsDAppViewController.swift, Cosmostation/Controller/Setting/SettingTableViewController.swift
In swift cases are exclusive, not need to break to avoid jumping into next cases
=> removed dead breaks

Cosmostation/Base/AppDelegate.swift, Cosmostation/Base/BaseData.swift
simplified empty if branch. simplify AppDelegate logic
=> Cleanup AppDelegate logic

Cosmostation/Base/UIKit/UIStoryboard+Instantiate.swift, Cosmostation/Controller/Main/AuthzDetailViewController.swift
remove duplicated guards. cleanup TransactionViewController instantiation
=> Cleanup TransactionViewController instantiation

Cosmostation/Base/UIKit/UIStoryboard+Instantiate.swift, Cosmostation/Controller/GenTx/FeeGrpcViewController.swift, Cosmostation/Controller/GenTx/StepGenTxViewController.swift, Cosmostation/Controller/GenTx/TransactionViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzClaimCommisstion1ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzClaimCommisstion4ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzClaimReward1ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzClaimReward4ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzDelegate1ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzDelegate2ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzDelegate5ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzRedelegate1ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzRedelegate2ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzRedelegate5ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzSend1ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzSend2ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzSend5ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzUndelegate1ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzUndelegate2ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzUndelegate5ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzVote1ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzVote5ViewController.swift
simplify data shared between viewcontrollers, use struct instead of plain properties
=> use struct instead of plain properties

Cosmostation/Controller/GenTx/FeeGrpcViewController.swift, Cosmostation/Controller/Main/ValidatorListViewController.swift, Cosmostation/Controller/Main/kava/DAppsListViewController.swift, Cosmostation/Controller/Main/okex/OkValidatorListViewController.swift, Cosmostation/Controller/Main/osmosis/OsmosisDAppViewController.swift, Cosmostation/Controller/Main/sif/SifDexDAppViewController.swift, Cosmostation/Controller/Main/starname/StarNameListViewController.swift
removed as iOS13 is always available. iOS deployment target is 13.5
=> removed if #available(iOS 13)

Cosmostation.xcodeproj/project.pbxproj, Cosmostation/Controller/GenTx/FeeGrpcViewController.swift, Cosmostation/Controller/GenTx/FeeGrpcViewController.xib, Cosmostation/Controller/Main/MainStoryboard.storyboard, Cosmostation/Controller/Main/ValidatorListViewController.swift, Cosmostation/Controller/Main/kava/DAppsListViewController.swift, Cosmostation/Controller/Main/kava/Kava.storyboard, Cosmostation/Controller/Main/okex/OkValidatorListViewController.swift, Cosmostation/Controller/Main/osmosis/Osmosis.storyboard, Cosmostation/Controller/Main/osmosis/OsmosisDAppViewController.swift, Cosmostation/Controller/Main/sif/SifChainDex.storyboard, Cosmostation/Controller/Main/sif/SifDexDAppViewController.swift, Cosmostation/Controller/Main/starname/StarName.storyboard, Cosmostation/Controller/Main/starname/StarNameListViewController.swift, Cosmostation/View/SegmentedControl.swift
created SegmentedControl component to avoid repeating UI setup.
migrate code to use SegmentedControl component
=> SegmentedControl 

Cosmostation/Controller/Main/MainTabViewController.swift
=> [IOSWL-610] Okc vote list bug fixed

Cosmostation.xcodeproj/project.pbxproj, Cosmostation/Controller/GenTx/authz/AuthzClaimReward1ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzClaimReward4ViewController.swift, Cosmostation/Controller/Main/AuthzDetailViewController.swift, Cosmostation/Model/GRPCExtensions/Cosmos_Distribution_V1beta1_DelegationDelegatorReward+Rewards.swift
used an extension to compute delegator rewards that matches a denom
=> refactor duplicated code.

Cosmostation/Base/Chains/ChainStationTest.swift
=> [IOSWL] update port wit station test

Cosmostation.xcodeproj/project.pbxproj, Cosmostation/Controller/Main/AuthzDetailViewController.swift, Cosmostation/Model/Array/Array+Sum.swift
removed duplicated code and moved to an extension
=> cleanup repeated sums

Cosmostation/Controller/Password/PasswordViewController.swift
I have checked and the software target is only iOS, If I am wrong discard it :)
=> remove dead if #available iOS8

Cosmostation/Base.lproj/Localizable.strings, Cosmostation/Base/BaseData.swift, Cosmostation/Controller/Main/AuthzDetailViewController.swift, Cosmostation/Model/ApiHistoryNewCustom.swift, Cosmostation/Utils/WUtils.swift, Cosmostation/ko.lproj/Localizable.strings
=> [IOSWL-617] Support Stride account type

Cosmostation/Utils/WUtils.swift
Update Caculating with Stride Vesting
=> [IOSWL-617] cacul update with stride vesting

Cosmostation/Controller/Main/AuthzDetailViewController.swift
Update Caculating Stride vesting with authz
=> [IOSWL-617] Update calculating with stride vesting

Cosmostation/Base/BaseData.swift, Cosmostation/Cell/AuthzExecuteCell.swift, Cosmostation/Cell/kava/EarnValidatorCell.swift, Cosmostation/Cell/txs/TxCommissionCell.swift, Cosmostation/Cell/txs/TxDelegateCell.swift, Cosmostation/Cell/txs/TxRedelegateCell.swift, Cosmostation/Cell/txs/TxRewardCell.swift, Cosmostation/Cell/txs/TxUndelegateCell.swift, Cosmostation/Cell/txs/kava/TxEarnCell.swift, Cosmostation/Controller/GenTx/authz/AuthzClaimCommisstion1ViewController.swift, Cosmostation/Controller/GenTx/authz/AuthzClaimCommisstion4ViewController.swift
small cleanup to avoid repeating code. removed filter and use directly first as filter will iterate over all the array and first will stop when find the expected addr
=> move search validator logic to a separate function into BaseData

Cosmostation/Cell/kava/HardListMyStatusCell.swift, Cosmostation/Controller/GenTx/kava/HtlcResultViewController.swift, Cosmostation/Controller/Main/MainTabViewController.swift, Cosmostation/Controller/Main/TxDetailgRPCViewController.swift, Cosmostation/Utils/WDP.swift, Cosmostation/Utils/WUtils.swift
removed some warnings and dead prints
=> removed warnings and dead code

Cosmostation/Controller/Password/AlphabetViewController.swift, Cosmostation/Controller/Password/DecimalViewController.swift, Cosmostation/Controller/Password/PasswordViewController.swift
fixed UIApplication.shared.beginIgnoringInteractionEvents() & UIApplication.shared.endIgnoringInteractionEvents() warnings
I have checked and it works Decimal and Alphabet view controllers but before merge, take a look at the comments that I left for PasswordViewController.
=> removed event warnings

Cosmostation.xcodeproj/project.pbxproj, Cosmostation/Base/BaseData.swift, Cosmostation/Controller/Main/AuthzDetailViewController.swift, Cosmostation/Utils/WUtils.swift
Update account type with desmos
=> [App-658] Update account type with desmos

Cosmostation.xcodeproj/project.pbxproj
automatic removal of duplications via xcode wizard
=> remove xcode warnings

Cosmostation.xcodeproj/project.pbxproj
fixes #209 
add ChainQuicksilver to CosmostationDev target
=> add missing file to CosmostationDev target #209

Cosmostation/Cell/AllValidatorCell.swift, Cosmostation/Cell/MyValidatorCell.swift, Cosmostation/Cell/OtherValidatorCell.swift, Cosmostation/Cell/ValidatorDetailMyActionCell.swift, Cosmostation/Cell/tokendetail/TokenDetailNativeCell.swift, Cosmostation/Cell/walletdash/WalletCrescentCell.swift, Cosmostation/Cell/walletdash/WalletCrytoCell.swift, Cosmostation/Cell/walletdash/WalletDesmosCell.swift, Cosmostation/Cell/walletdash/WalletGuideCell.swift, Cosmostation/Cell/walletdash/WalletInflationCell.swift, Cosmostation/Cell/walletdash/WalletIovCell.swift, Cosmostation/Cell/walletdash/WalletIrisCell.swift, Cosmostation/Cell/walletdash/WalletKavaCell.swift, Cosmostation/Cell/walletdash/WalletOsmoCell.swift, Cosmostation/Cell/walletdash/WalletPriceCell.swift, Cosmostation/Cell/walletdash/WalletSifCell.swift, Cosmostation/Cell/walletdash/WalletStationCell.swift, Cosmostation/Cell/walletdash/WalletStrideCell.swift
replace if with guard and some force unwraps
=> cleanup force unwraps `!`

Cosmostation/Base/Chains/ChainBand.swift, Cosmostation/Base/Chains/ChainDesmos.swift, Cosmostation/Base/Chains/ChainIris.swift, Cosmostation/Base/Chains/ChainProvenance.swift, Cosmostation/Base/Chains/ChainQuicksilver.swift, Cosmostation/Base/Chains/ChainStarname.swift, Cosmostation/Controller/Main/MainTabWalletViewController.swift
=> [App-664] Support new authz chain

Cosmostation/Cell/AuthzExecuteCell.swift, Cosmostation/Cell/AuthzGranteeCell.swift, Cosmostation/Cell/AuthzGranterCell.swift, Cosmostation/Cell/ClaimRewardAllCell.swift, Cosmostation/Cell/ValidatorDetailCell.swift, Cosmostation/Cell/ValidatorDetailMyDetailCell.swift, Cosmostation/Cell/VoteCell.swift, Cosmostation/Utils/WDP.swift, Cosmostation/Utils/WKey.swift, Cosmostation/Utils/WUtils.swift
replace if with guard and some force unwraps
=> cleanup force unwraps `!` (3)

Cosmostation/Base.lproj/Localizable.strings, Cosmostation/Cell/AuthzExecuteCell.swift, Cosmostation/Controller/Main/AuthzDetailViewController.swift, Cosmostation/Utils/WUtils.swift, Cosmostation/ko.lproj/Localizable.strings
remove force unwraps. remove duplicated code
=> Remove force unwraps & cleanup

Cosmostation/Base/BaseData.swift, Cosmostation/Base/BaseNetWork.swift, Cosmostation/Base/BaseViewController.swift, Cosmostation/Controller/Main/AuthzDetailViewController.swift, Cosmostation/Controller/Main/TxDetailgRPCViewController.swift
=> removed force unwraps

Cosmostation/Controller/Main/VoteDetailsViewController.swift
=> [App-668] vote detail bug fixed

Cosmostation/Base/BaseNetWork.swift, Cosmostation/Dao/Param.swift
=> [APP-670] Update param url with V2

Cosmostation/Controller/Main/MainTabTokenViewController.swift
=> [APP-672] asset crash bug fixed

Cosmostation/Base/Chains/BaseChain.swift, Cosmostation/Base/Store/Authz/AuthzServiceLocator.swift, Cosmostation/Base/Store/Authz/GranteeGrantsAction.swift, Cosmostation/Base/Store/Authz/GranteeGrantsReducer.swift, Cosmostation/Base/Store/Authz/GranteeGrantsState.swift, Cosmostation/Base/Store/State.swift, Cosmostation/Base/Store/Store.swift, Cosmostation/Controller/Main/AuthzListViewController.swift, Cosmostation/Controller/Main/MainTabWalletViewController.swift
This PR is related to the issue #237 
Improvements related to the removal of the access to the data directly from the ViewController
=> AuthzListViewController removed static access to data

Cosmostation/Controller/Setting/MnemonicCreateViewController.swift, Cosmostation/Controller/Setting/MnemonicRestoreViewController.swift, Cosmostation/Controller/Setting/WalletDeriveViewController.swift, Cosmostation/en.lproj/Localizable.strings, Cosmostation/ja.lproj/Localizable.strings, Cosmostation/ko.lproj/Localizable.strings
init func with Set Mnemonic Name
=> [APP-667] init func with Set Mnemonic Name

Cosmostation/Controller/Main/MainTabViewController.swift, Cosmostation/Model/SupportPool.swift
pool type init with osmosis list
=> [APP-690] pool type init with osmosis list

Cosmostation/Base/Chains/ChainMars.swift, Cosmostation/Dao/Param.swift
inflation & apr init with Cudos
=> [APP-693] inflation & apr init with Cudos

Cosmostation/Dao/Param.swift
=> [APP-696] new Caculate with axelar apr

Cosmostation/Dao/Param.swift
Support inflaion & apy with Sommelier
=> [APP-704] Support inflaion & apy with Sommelier

Cosmostation.xcodeproj/project.pbxproj, Cosmostation/Base/Chains/ChainCosmos.swift, Cosmostation/Controller/Main/MainTabWalletViewController.swift, Cosmostation/en.lproj/Localizable.strings
Support Kado Money with cosmos
=> [APP-737] Support Kado Money with cosmos

Cosmostation/Dao/Param.swift
Init inflation & apr with quicksilver
=> [APP-739] init inflation & apr with quicksilver

Cosmostation/Controller/GenTx/FeeGrpcViewController.swift
=> [APP-742] out of gas bug fixed with Ixo

Cosmostation/Utils/WUtils.swift
=> [APP-756] noble fee display bug fixed

Cosmostation/Controller/GenTx/FeeGrpcViewController.swift, Cosmostation/Controller/Main/MyValidatorViewController.swift
=> [APP-763]Update Calculating gas

Cosmostation/Dao/Param.swift
Update calculating Omniflix Apr
=> [APP-766] Update calculating omniflix

Cosmostation/Base/BaseNetWork.swift, Cosmostation/Controller/GenTx/kava/HtlcResultViewController.swift, Cosmostation/Model/KavaModel/KavaSwapParam.swift, Cosmostation/Model/KavaModel/KavaSwapSupply.swift
=> [APP-771] bep3 bug fixed with kava

Cosmostation/Base/BaseNetWork.swift, Cosmostation/Controller/GenTx/kava/CdpDeposit1ViewController.swift, Cosmostation/Controller/GenTx/kava/CdpDrawDebt1ViewController.swift, Cosmostation/Controller/GenTx/kava/CdpDrawDebt1ViewController.xib, Cosmostation/Controller/GenTx/kava/CdpDrawRepay1ViewController.swift, Cosmostation/Controller/GenTx/kava/CdpWithdraw1ViewController.swift, Cosmostation/Controller/Main/kava/CdpDetailViewController.swift, Cosmostation/Model/KavaModel/KavaCdpDeposits.swift
=> [APP-772] cdp bug fixed with kava

Cosmostation.xcodeproj/project.pbxproj, Cosmostation/Base/BaseConstant.swift, Cosmostation/Base/BaseData.swift, Cosmostation/Cell/AssetCell.swift, Cosmostation/Cell/tokendetail/TokenDetailCustomCell.swift, Cosmostation/Cell/tokendetail/TokenDetailCustomCell.xib, Cosmostation/Cell/tokendetail/TokenDetailVestingDetailCell.swift, Cosmostation/Cell/walletdash/WalletNeutronCell.swift, Cosmostation/Cell/walletdash/WalletNeutronCell.xib, Cosmostation/Controller/Main/MainTabViewController.swift, Cosmostation/Controller/Main/token/StakingTokenGrpcViewController.swift, Cosmostation/Dao/Cw20NeutronVestingReq.swift, Cosmostation/Dao/Cw20NeutronVestingRes.swift, Cosmostation/en.lproj/Localizable.strings, Cosmostation/ja.lproj/Localizable.strings, Cosmostation/ko.lproj/Localizable.strings
Vesting Amount init wiht Neutron
=> [APP-773] vesting init with neutron

Cosmostation/Controller/Main/MyValidatorViewController.swift
=> [IOSWL] update chihuahua fee

Cosmostation/Controller/Main/MainTabViewController.swift, Cosmostation/Dao/Cw20NeutronVestingRes.swift
Update neutron vesting amount calculating
=> [APP-781] Update neutron vesting amount calculating

Cosmostation/Base/Chains/ChainArchway.swift
=> [APP-783] Support authz with archway

Cosmostation/Controller/GenTx/FeeGrpcViewController.swift
=> [APP-786] Update gas with Chihuahua

Cosmostation.xcodeproj/project.pbxproj, Cosmostation/Base/BaseConstant.swift, Cosmostation/Base/BaseData.swift, Cosmostation/Base/BaseNetWork.swift, Cosmostation/Controller/Main/CommonWCViewController.swift, Cosmostation/Controller/Main/MainTabViewController.swift, Cosmostation/Model/SupportConfig.swift
=> [APP] support custom chain dapp

Cosmostation/Dao/Param.swift
=> [APP-785] Update apr onomy && archway

Cosmostation/Base/BaseConstant.swift, Cosmostation/Controller/Main/CommonWCViewController.swift
Support dapp astroport with injective
=> [APP-788] Support dapp astroport with injective

Cosmostation/Controller/GenTx/kava/HtlcResultViewController.swift
=> [APP-792] Timing fix with bep3

Cosmostation/Controller/Main/CommonWCViewController.swift
=> [APP-790] support not 118 wallet WC

Cosmostation/Cell/txs/TxDelegateCell.swift, Cosmostation/Cell/txs/TxRedelegateCell.swift, Cosmostation/Cell/txs/TxUndelegateCell.swift, Cosmostation/Utils/WUtils.swift
=> [APP-789] Auto reward bug fixed

Cosmostation/Controller/Main/CommonWCViewController.swift, Cosmostation/Controller/Main/CommonWCViewController.xib
Resize refresh button with dapp
=> [APP-791] resize refresh button with dapp

Cosmostation/Controller/Main/CommonWCViewController.swift
=> [APP-793] support inj ethermint address

Cosmostation/Controller/Main/CommonWCViewController.swift
=> [APP-793] dapp crashed bug fixed

Cosmostation/Controller/Main/CommonWCViewController.swift
=> [APP-794] Update astroport connect

Cosmostation/Controller/Main/CommonWCViewController.swift
=> [APP-794] Support Signdoc request

Cosmostation/Controller/Main/MainTabWalletViewController.swift, Cosmostation/Controller/Setting/SettingTableViewController.swift
=> [APP-795] Update notice url

Cosmostation/Controller/Main/CommonWCViewController.swift, Cosmostation/Dao/Cw20IcnsByNameReq.swift, Cosmostation/Model/ApiHistoryNewCustom.swift
wc bug fixed & arch icns bug fixed
=> [APP] wc bug fixed & arch icns bug fixed

Cosmostation/Cell/tokendetail/TokenDetailVestingDetailCell.swift, Cosmostation/Utils/WDP.swift, Cosmostation/Utils/WUtils.swift
Neutron vesting duration bug fixed
=> [APP-802] Neutron vesting duration bug fixed

Cosmostation/Dao/Param.swift
=> [APP-801] Update Stargaze Apr

Cosmostation/Controller/GenTx/common/Transfer1ViewController.swift
=> [APP-805] Compare path before chain

Cosmostation/Controller/GenTx/FeeGrpcViewController.swift, Cosmostation/Controller/GenTx/common/Transfer5ViewController.swift, Cosmostation/Controller/Main/MainTabWalletViewController.swift, Cosmostation/Crypto/Signer.swift
=> [APP-v2] ibc transfer bug fixed

Cosmostation/Controller/Setting/MnemonicRestoreViewController.swift
=> [APP] restore bug fixed

Cosmostation/Cell/walletdash/WalletNeutronCell.xib
=> [Hot-fix] invisible neutron defi

Cosmostation/Base/Chains/ChainCryptoorg.swift
=> [APP-810] update chainname with cronos

Cosmostation/Base/Chains/ChainCryptoorg.swift, Cosmostation/Controller/Setting/WalletDeriveViewController.swift
=> [APP] cronos pos searching fix

Cosmostation/Controller/Main/DappDetailVC.swift, Cosmostation/Controller/Main/DappDetailVC.xib, Cosmostation/Controller/Sheet/TxSignRequestSheet.swift
=> [APP-v2] init disconnect session dapp

Cosmostation/Controller/Main/DappStartVC.swift
=> [APP-841] dapp session bug fixed

Cosmostation/Base/AppDelegate.swift, Cosmostation/Controller/Main/DappDetailVC.swift, Cosmostation/Controller/Sheet/TxSignRequestSheet.swift
Improve Dapp & support disconnect method
=> [APP-858] improve sign fee data & init disconnect method

Cosmostation.xcodeproj/project.pbxproj, Cosmostation/Controller/Main/CosmosClass/CosmosCryptoVC.swift, Cosmostation/Controller/Main/EvmClass/EvmAssetVC.swift, Cosmostation/UI/Cell/AssetCell.swift, Cosmostation/UI/View/SearchBarWithTopPadding.swift
List count 0 => tableView section header delete
count less than 15 => searchBar hidden
Add searchBar Top Padding
=> [APP-989] Fix SearchBar

Cosmostation/Controller/Setting/ChainListVC.swift
=> [APP-1017] Fix ChainListVC tableView section header title

Cosmostation/Controller/Main/AllChainClaimStartVC.swift, Cosmostation/Controller/Main/AllChainClaimStartVC.xib, Cosmostation/Fetcher/CosmosFetcher.swift, Cosmostation/Resource/Color.xcassets/_color09.colorset/Contents.json, Cosmostation/Resource/Color.xcassets/_colorBg.colorset/Contents.json, Cosmostation/UI/Cell/ClaimAllChainCell.swift, Cosmostation/UI/Cell/ClaimAllChainCell.xib
if changed address, display CHANGED
=> [APP-1028] Design chain reward address

Cosmostation/Controller/Main/MajorClass/Sui/Cell/SuiStakingCell.xib, Cosmostation/Controller/Main/MajorClass/Sui/SuiStake.swift, Cosmostation/Controller/Main/MajorClass/Sui/SuiStake.xib, Cosmostation/Controller/Main/MajorClass/Sui/SuiStakingInfoVC.swift, Cosmostation/Controller/Main/MajorClass/Sui/SuiUnstake.xib
fix typo, refresh, init data, stake action
=> [APP-1021] Fix Sui Stake

Cosmostation/Controller/Main/GenTx/CommonTransfer.swift, Cosmostation/Controller/Sheet/TxMemoSheet.swift, Cosmostation/en.lproj/Localizable.strings, Cosmostation/ja.lproj/Localizable.strings, Cosmostation/ko.lproj/Localizable.strings
Fix naming : memo -> OP_RETURN
Change color to red when over 80 bytes
=> [APP-1034] fix btc op_return label

Cosmostation/Chains/BaseChain.swift, Cosmostation/Controller/Main/CosmosClass/GenTx/CosmosDelegate.swift, Cosmostation/Controller/Main/CosmosClass/GenTx/CosmosRedelegate.swift, Cosmostation/Controller/Main/CosmosClass/GenTx/CosmosUndelegate.swift, Cosmostation/Controller/Main/CosmosClass/GenTx/Kava/KavaEarnDepositAction.swift, Cosmostation/Controller/Main/CosmosClass/Kava/Cell/KavaEarnListCell.swift, Cosmostation/Controller/Main/EvmClass/GenTx/EvmDelegate.swift, Cosmostation/Controller/Main/EvmClass/GenTx/EvmRedelegate.swift, Cosmostation/Controller/Main/EvmClass/GenTx/EvmUndelegate.swift, Cosmostation/Controller/Sheet/SheetCell/SelectValidatorCell.swift, Cosmostation/Fetcher/CosmosFetcher.swift, Cosmostation/UI/Cell/StakeDelegateCell.swift, Cosmostation/UI/Cell/StakeUnbondingCell.swift
=> [APP-1054] Feat gaia v20

Cosmostation/Base/BaseVC.swift, Cosmostation/Controller/Main/CosmosClass/CosmosCryptoVC.swift, Cosmostation/Controller/Main/EvmClass/EvmAssetVC.swift, Cosmostation/Controller/Main/PortfolioVC.swift
- Initialize token amount list when changing account
- Add an error toast message when sending a zero amount token
- Update token sorting
=> [APP-1063] Refactoring token select list sheet

Cosmostation/Controller/Main/CosmosClass/GenTx/CosmosRedelegate.swift
+ Fix fromValidator and toValidator to not be the same
=> [APP-1080] Fix redelegate validator list

README.md
Corrected "tendermint" to "Tendermint" for proper capitalization.
=> Fixed capitalization.

Cosmostation/Fetcher/BtcFetcher.swift
=> Update btc mempoolUrl

Cosmostation/Chains/ClassCosmos/ChainAssetMantle.swift, Cosmostation/Chains/ClassCosmos/ChainJuno.swift, Cosmostation/Chains/ClassCosmos/ChainKyve.swift, Cosmostation/Chains/ClassCosmos/ChainNyx.swift, Cosmostation/Chains/ClassCosmos/ChainPassage.swift, Cosmostation/Chains/ClassCosmos/ChainTeritori.swift, Cosmostation/Chains/ClassCosmos/ChainUmee.swift, Cosmostation/Chains/ClassEVM/ChainEvmosEVM.swift
Update Endpoint with not support chain
=> [APP-1075] Update endpoint with not support chain
